@baseUrl=http://localhost:8787/movements

# (name, difficulty, description, extraNotes)

### create new movement
POST {{baseUrl}}
Content-Type: application/json

{
  "movementName": "Test Movement",
  "movementSummary": "Test summary",
  "movementDescription": "Test description",
  // fields using schema's controlled choices
  "movementExecution": "Static",
  "movementDemand": ["Strength"],
  "movementTerrain": ["Slab"],
  // remaining required fields
  "movementStatus": "Draft",
  "movementWhenToUse": "Test when to use",
  "movementHowToPerform": "Test how to perform",
  "movementCommonMistakes": "Test common mistakes",
  "movementTags": ["Test tags"]
}


### get movements
GET {{baseUrl}}


