@baseUrl=http://localhost:8787/movements

# (name, difficulty, description, extraNotes)

### create new movement
POST {{baseUrl}}
Content-Type: application/json

{
  "movementName": "Test Movement",
  "movementSummary": "Test summary",
  "movementDescription": "Test description",
  "movementExecution": "Static",
  "movementDemand": ["Strength"],
  "movementTerrain": ["Slab"],
  "movementStatus": "Draft",
  "movementWhenToUse": "Test when to use",
  "movementHowToPerform": "Test how to perform",
  "movementCommonMistakes": "Test common mistakes",
  "movementTags": ["Test tags"]
}

### get movements
GET {{baseUrl}}

### get movement by id
GET {{baseUrl}}/

### update movement by id
PATCH {{baseUrl}}/6a848788f29e21d2cae475ce
# tells Express: I'm sending JSON data in the request body
Content-Type: application/json 

# what I want changed
{
  "movementStatus": "draft"
}

